language: node_js
notifications:
  email:
    on_success: never
    on_failure: change
node_js:
  - "node"
  - "8"
deploy:
  provider: heroku
  app: blooming-spire-30217
  on:
    repo: Bogdansky/cwp-34
before_script:
  - npm install